# Site settings
title: facts & figures
header-img: img/home-bg.jpg
email: juan.carlos.mayo.martinez@gmail.com
# "Write your site description here. It will be used as your sites meta description as well!"
description: "Data analysis and things that come my way"
baseurl: ""
url: "http://jcarlosmayo.github.io"
twitter_username: jcarlosmayo
github_username:  jcarlosmayo
facebook_username:  jcarlos.mayo

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
