# Site settings
title: facts & figures
header-img: img/home-bg.jpg
email: juancarlos.mayo@iki.fi
# "Write your site description here. It will be used as your sites meta description as well!"
description: "Data analysis and things that come my way"
baseurl: ""
url: "http://jcarlosmayo.github.io"
github_username:  jcarlosmayo

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins:
  - jekyll-paginate
paginate: 5
